### ISSUE TITLE
Fails to build on MacOS Catalina 10.15

### ISSUE THREAD

**Issue by selfagency** [PeculiarVentures/node-webcrypto-ossl#148]
```
error /Users/daniel/code/kifa-micro/node_modules/node-webcrypto-ossl: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/daniel/code/kifa-micro/node_modules/node-webcrypto-ossl
[...]
../src/ec/ec_jwk.cpp:48:11: error: use of undeclared identifier 'EC_POINT_get_affine_coordinates'; did you mean 'EC_POINT_get_affine_coordinates_GFp'?
        if (1 != EC_POINT_GET_AFFINE_COORDINATES(group, point, x.Get(), y.Get(), NULL)) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 EC_POINT_get_affine_coordinates_GFp
../src/ec/ec_jwk.cpp:45:41: note: expanded from macro 'EC_POINT_GET_AFFINE_COORDINATES'
#define EC_POINT_GET_AFFINE_COORDINATES EC_POINT_get_affine_coordinates
                                        ^
/Users/daniel/.node-gyp/10.15.3/include/node/openssl/ec.h:494:5: note: 'EC_POINT_get_affine_coordinates_GFp' declared here
int EC_POINT_get_affine_coordinates_GFp(const EC_GROUP *group,
    ^
1 error generated.
make: *** [Release/obj.target/nodessl/src/ec/ec_jwk.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/daniel/.nodenv/versions/10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/daniel/.nodenv/versions/10.15.3/bin/node" "/Users/daniel/.nodenv/versions/10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/daniel/code/kifa-micro/node_modules/node-webcrypto-ossl
```

**Comment by microshine** [comment]
@selfagency What is your NodeJS version?

**Comment by microshine** [comment]
@selfagency I've published a new version `+ node-webcrypto-ossl@1.0.47`. Can you try it and close issue?

**Comment by selfagency** [comment]
I'm using 10.15.3. And the update worked. Thanks!
